### ISSUE TITLE
the home tab is useless. lose it.

### ISSUE THREAD

**Issue by ghost** [demon36/tparted#5]

**Comment by demon36** [comment]
it was intended to creep users out but ok

**Comment by demon36** [comment]
removed here https://github.com/demon36/tparted/commit/40536c74d35349449e63771b8cad32886ff61f3f

**Comment by ghost** [comment]
in the commit message if you say "fix #5 and did changes and stuff" github will automatically close the issue and will say that you referenced this issue :smile:

**Comment by demon36** [comment]
niiice
