### ISSUE TITLE
why need both email and username? isn't email unique enough?

### ISSUE THREAD

**Issue by ghost** [demon36/tparted#8]
Why need full name and picture. are you planning on having some kind of interaction between users in the future?

**Comment by demon36** [comment]
it was a college project and I was forced to implement features i didnt like

**Comment by ghost** [comment]
oh

**Comment by demon36** [comment]
I believe logging in with user name is easier
fullname field and profile pic are removed here https://github.com/demon36/tparted/commit/40536c74d35349449e63771b8cad32886ff61f3f
